title: NewDeaBox
description: NDB Blog
url: https://newdeaboxgroup.github.io
assets: https://newdeaboxgroup.github.io/assets
keywords: ["NDB", "Blog", "NewDeaBox", "NewDeaBoxGroup", "New Dea Box", "New Dea Box Group", "ndb", "newdeabox", "newdeaboxgroup"]
timezone: Asia/Seoul
permalink: pretty
encoding: utf-8
incremental: true # Test

about: "NewDeaBoxGroup Github page"

author:
  disqus: newdeaboxgroup
  email: 
  github: NewDeaBoxGroup # required
  google_analytics: UA-79653675-2
  name: NewDeaBoxGroup # required
  telegram: newdeabox

paginate: 10
paginate_path: "/blog/page/:num/"

collections:
  notis:
    output: true
    permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "notis"
    values:
      layout: "post"

kramdown:
  input: GFM

sass:
  style: compressed
